In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("C:/Users/Hp/Downloads/customer_shopping_behavior.csv")
data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
data.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [4]:
data.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
data.isna().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
data["Review Rating"]=data.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))
data.isna().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
data.shape

(3900, 18)

In [8]:
data.dtypes

Customer ID                 int64
Age                         int64
Gender                     object
Item Purchased             object
Category                   object
Purchase Amount (USD)       int64
Location                   object
Size                       object
Color                      object
Season                     object
Review Rating             float64
Subscription Status        object
Shipping Type              object
Discount Applied           object
Promo Code Used            object
Previous Purchases          int64
Payment Method             object
Frequency of Purchases     object
dtype: object

In [9]:
data.duplicated().sum()

np.int64(0)

In [10]:
clean_data=data.copy()
print(clean_data.columns)

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [11]:
clean_data.columns=clean_data.columns.str.lower().str.strip().str.replace(' ','_')

In [12]:
print(clean_data.columns)

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [13]:
clean_data["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [14]:
clean_data['category'].unique()

array(['Clothing', 'Footwear', 'Outerwear', 'Accessories'], dtype=object)

In [15]:
clean_data['payment_method'].unique()

array(['Venmo', 'Cash', 'Credit Card', 'PayPal', 'Bank Transfer',
       'Debit Card'], dtype=object)

In [16]:
clean_data['purchase_amount_(usd)'].str.replace('(usd)','t')

AttributeError: Can only use .str accessor with string values!

In [ ]:
clean_data.info()

In [ ]:
clean_data['discount_applied']==clean_data['promo_code_used']

In [ ]:
clean_data.drop('promo_code_used',axis=1,inplace=True)

In [17]:
clean_data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [18]:
clean_data.shape

(3900, 18)

In [23]:
label=['Young Adults','Adults','Middle-aged Adults','Older Adults','Seniors']
clean_data['age_group']=pd.cut(clean_data['age'],bins=[0,25,40,55,65,100],labels=label)
print(age_group)

0       Middle-aged Adults
1             Young Adults
2       Middle-aged Adults
3             Young Adults
4       Middle-aged Adults
               ...
3895                Adults
3896    Middle-aged Adults
3897    Middle-aged Adults
3898    Middle-aged Adults
3899    Middle-aged Adults
Name: age, Length: 3900, dtype: category
Categories (5, object): ['Young Adults' < 'Adults' < 'Middle-aged Adults' < 'Older Adults' < 'Seniors']

In [20]:
frequency_mapping={
    'fortnighly':14,
    'Weekly'    :7,
    'Monthly'   :30,
    'Quarterly' :90,
    'Bi-Weekly' :365,
    'Every 3 Months' :90
}
clean_data['purchases_frequency_days']=clean_data['frequency_of_purchases'].map(frequency_mapping)

In [21]:
clean_data[['purchases_frequency_days','frequency_of_purchases']]

      purchases_frequency_days frequency_of_purchases
0                          NaN            Fortnightly
1                          NaN            Fortnightly
2                          7.0                 Weekly
3                          7.0                 Weekly
4                          NaN               Annually
...                        ...                    ...
3895                       7.0                 Weekly
3896                     365.0              Bi-Weekly
3897                      90.0              Quarterly
3898                       7.0                 Weekly
3899                      90.0              Quarterly

[3900 rows x 2 columns]

In [14]:
!pip install --upgrade pip

Requirement already satisfied: pip in c:\users\hp\anaconda3\lib\site-packages (25.1)
Collecting pip
  Using cached pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Using cached pip-26.2.1-py3-none-any.whl (1.8 MB)

ERROR: To modify pip, please run the following command:
C:\Users\Hp\anaconda3\python.exe -m pip install --upgrade pip

In [1]:
!pip install psycopg2-binary sqlalchemy --only-binary :all:

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/psycopg2-binary/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/psycopg2-binary/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/psycopg2-binary/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/psycopg2-binary/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/psycopg2-binary/
ERROR: Could not find a version that satisfies the requirement psycopg2-binary (from versions: none)
ERROR: No matching distribution found for psycopg2-binary

In [2]:
import sys; print(sys.executable)
!{sys.executable} -m pip install sqlalchemy

C:\Users\Hp\anaconda3\envs\python-starter\python.exe
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.52-cp313-cp313-win_amd64.whl.metadata (9.9 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.5.5-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Hp\anaconda3\envs\python-starter\Lib\site-packages (from sqlalchemy) (4.16.0)
Using cached sqlalchemy-2.0.52-cp313-cp313-win_amd64.whl (2.2 MB)
Downloading greenlet-3.5.5-cp313-cp313-win_amd64.whl (324 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.5.5 sqlalchemy-2.0.52

In [4]:
!{sys.executable} -m pip install psycopg2-binary

Collecting psycopg2-binary
  Using cached psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Using cached psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [24]:
!pip show  sqlalchemy
from sqlalchemy import create_engine
username = "postgres"
password = "heesung1#"
host = "localhost"
port = "5432"
database = "customer_behaviour"
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
table_name="customer"
clean_data.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"Data succesfully loaded into table '{table_name}' in database '{database}'.")

Name: SQLAlchemy
Version: 2.0.39
Summary: Database Abstraction Library
Home-page: https://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: C:\Users\Hp\anaconda3\Lib\site-packages
Requires: greenlet, typing-extensions
Required-by: aext-project-filebrowser-server, alembic
Data succesfully loaded into table 'customer' in database 'customer_behaviour'.